""".env helpers — ported from scripts/lib/env.sh (#7, Stage 2).

Only `get()` (bash `_env_get`) is ported so far: it is the one piece of env.sh
with live Python consumers (ollama.py, secrets.py), so consolidating it here
removes the duplicate copies those modules carried. The rest of env.sh
(prepare_env / secret self-heal / compose-.env mirror / gen_secret) is consumed
only by the still-bash start/install verbs and is deferred until those are ported
— porting it now would be dead code.
"""

import secrets

from . import config

ENV_FILE = config.ENV_FILE
COMPOSE_ENV_FILE = config.COMPOSE_ENV_FILE

# _sync_compose_env's DO-NOT-EDIT banner (config.sh printf block): "# " + 76 '='.
_COMPOSE_ENV_BANNER = (
    "# " + "=" * 76,
    "# DO NOT EDIT — generated by setup.sh from the root .env (single source of truth).",
    "# Edit ./.env and re-run setup.sh (start/restart) to regenerate this file.",
    "# " + "=" * 76,
)


def get(key: str) -> str:
    """Mirror env.sh _env_get: `grep -E "^KEY=" .env | cut -d= -f2-` — the value
    after the FIRST '='; "" when the key is absent or .env is unreadable. Multiple
    matching lines yield their values joined by newlines, exactly like the pipe.
    (Keys are fixed identifiers with no regex metachars, so a prefix match is
    equivalent to bash's `^KEY=` anchor.)
    """
    try:
        text = ENV_FILE.read_text(encoding="utf-8")
    except OSError:
        return ""
    out = [line.split("=", 1)[1] for line in text.splitlines() if line.startswith(f"{key}=")]
    return "\n".join(out)


def gen_secret(nbytes: int = 32) -> str:
    """bash gen_secret: 2*nbytes hex chars. bash uses `openssl rand -hex` with a
    /dev/urandom fallback; secrets.token_hex is cross-platform, cryptographically
    secure, and needs neither — the observable contract (length + [0-9a-f]) holds."""
    return secrets.token_hex(nbytes)


def sync_compose_env() -> None:
    """bash _sync_compose_env: mirror the root .env to COMPOSE_ENV_FILE (the path
    docker compose reads) with a DO-NOT-EDIT banner. A COPY, not a symlink, for
    Windows + Pi. Silent. The .env body is passed through as raw bytes (like
    `cat`) so no line-ending translation can diverge from bash."""
    COMPOSE_ENV_FILE.parent.mkdir(parents=True, exist_ok=True)
    try:
        body = ENV_FILE.read_bytes()
    except OSError:
        body = b""
    banner = ("\n".join(_COMPOSE_ENV_BANNER) + "\n").encode("utf-8")
    with COMPOSE_ENV_FILE.open("wb") as fh:
        fh.write(banner + body)
    try:  # chmod 600 best-effort — no-op on Windows, mirrors bash's `|| true`
        COMPOSE_ENV_FILE.chmod(0o600)
    except OSError:
        pass
